# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"

reviews:
  review_status: true
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - dev_komo
      - coderabbit
